import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:asterlink/core/json.dart';
import 'package:asterlink/data/uploads/weiyun_hash.dart';
import 'package:asterlink/domain/uploads.dart';

void main() {
  // Generated by Go's standard crypto/sha1 MarshalBinary, following the SDK's
  // little-endian checkpoint protocol. The last block uses the padded digest.
  final vectors =
      jsonDecode(
            File('test/fixtures/weiyun-upload-hashes.json').readAsStringSync(),
          )
          as List;
  for (final raw in vectors) {
    final vector = asJson(raw), size = vector.integer('size');
    test(
      'Weiyun hashes match Go at $size bytes with irregular stream chunks',
      () async {
        final bytes = Uint8List.fromList(
          List.generate(size, (i) => (i * 31 + i ~/ 7) % 256),
        );
        final source = UploadFile(
          name: 'sample.bin',
          size: size,
          read: (start, end) async* {
            for (var i = start; i < end; i += 7777) {
              yield Uint8List.sublistView(bytes, i, (i + 7777).clamp(i, end));
            }
          },
        );
        final plan = await WeiyunHash.plan(source, null);
        expect(plan, vector.obj('plan'));
        expect(
          plan.list('block_info_list').last.str('sha'),
          sha1.convert(bytes).toString(),
        );
        final tail = base64Decode(plan.str('check_data'));
        expect(tail, bytes.sublist(bytes.length - tail.length));
      },
    );
  }
}
